version: '3.7'
services:
  db:
    image: postgres:13
    ports:
      - "127.0.0.1:25432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  redis:
    image: redis:6.2-alpine3.14
    command: redis-server --appendonly yes
    ports:
      - "127.0.0.1:26379:6379"
    volumes:
      - redis:/data
volumes:
  db:
  redis:
